# Write your MySQL query statement below
SELECT E.EMPLOYEE_ID, E.NAME, 
COUNT(R.EMPLOYEE_ID) AS REPORTS_COUNT,
ROUND(AVG(R.AGE), 0) AS AVERAGE_AGE
FROM EMPLOYEES E JOIN EMPLOYEES R
ON E.EMPLOYEE_ID = R.REPORTS_TO
GROUP BY E.EMPLOYEE_ID
ORDER BY E.EMPLOYEE_ID;